### ISSUE TITLE
Serialize routes

### ISSUE THREAD

**Issue by m1guelpf** [davidpiesse/nova-maintenance-mode#2]
You're providing rutes as closures, and that prevents us from serializing routes

**Comment by davidpiesse** [comment]
Is the change to bring back the controller and move the logic in that?
I had planned for this so it should be an easy fix.

**Comment by m1guelpf** [comment]
Yeah, that'd fix it

**Comment by davidpiesse** [comment]
Just about to push a new release with the logic moved to controller.
Thanks @m1guelpf  👍
